apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: python-ui
  template:
    metadata:
      labels:
        app: pythin-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: python-ui
        ports:
        - containerPort: 80
