
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-ui
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: python-ui
  template:
    metadata:
      labels:
        app: python-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: python-ui
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: 1
            memory: 4Gi"
        ports:
        - containerPort: 80
