apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: qb-billing-service
  name: hpa
spec:
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - object:
      describedObject:
        apiVersion: apps/v1
        kind: Deployment
        name: qb-billing-service
      metric:
        name: namespace_app_pod_cpu_utilization
      target:
        type: Value
        value: 70
    type: Object
  - object:
      describedObject:
        apiVersion: apps/v1
        kind: Deployment
        name: qb-billing-service
      metric:
        name: namespace_app_pod_jvm_memory_heap_utilization
      target:
        type: Value
        value: 75
    type: Object
  - object:
      describedObject:
        apiVersion: apps/v1
        kind: Deployment
        name: qb-billing-service
      metric:
        name: namespace_app_pod_tomcat_threads_busy_percentage
      target:
        type: Value
        value: 70
    type: Object
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qb-billing-service-appd-deployment
