apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: python-ui
  name: hpa
spec:
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - object:
      describedObject:
        apiVersion: apps/v1
        kind: Deployment
        name: python-ui
      metric:
        name: namespace_app_pod_cpu_utilization
      target:
        type: Value
        value: 70
    type: Object
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-ui
