apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: python-ui
spec:
  maxReplicas: 6
  minReplicas: 2
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: example-rollout
  targetCPUUtilizationPercentage: 80
